[package]
name = "termkeeper-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5"
tui = { version = "0.17", features = ["termion"] }
failure = "0.1"
rand = "0.8"

